### ISSUE TITLE
Out of memory after some iterations of validation

### ISSUE THREAD

**Issue by yijicheng** [taconite/arah-release#11]
Restoring states from the checkpoint path at out/arah-zju/ZJUMOCAP-313_4gpus/checkpoints/last.ckpt                                                                                               
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]                                                                                                                                          
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]                                                                                                                                          
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]                                                                                                                                          
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]                                                                                                                                          
Loaded model weights from checkpoint at out/arah-zju/ZJUMOCAP-313_4gpus/checkpoints/last.ckpt                                                                                                    
Validating:  15%|████████████████████▎                                                                                                                   | 513/3434 [2:04:33<16:18:51, 20.11s/it]
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt                                                          
    return trainer_fn(*args, **kwargs)                                                                                                                                                           
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _validate_impl                                                                      
    results = self._run(model, ckpt_path=self.validated_ckpt_path)                                                                                                                               
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run                                                                               
    self._dispatch()                                                                                                                                                                             
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch                                                                          
    self.training_type_plugin.start_evaluating(self)                                                                                                                                             
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 206, in start_evaluating                                         
    self._results = trainer.run_stage()                                                                                                                                                          
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in run_stage                                                                          
    return self._run_evaluate()                                                                                                                                                                  
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1334, in _run_evaluate                                                                      
    eval_loop_results = self._evaluation_loop.run()                                                                                                                                              
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run                                                                                      
    self.advance(*args, **kwargs)                                                                                                                                                                
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance                                                            
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)                                                                                           
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run                                                                                      
    self.advance(*args, **kwargs)                                                                                                                                                                
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance                                                           
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)                                                                                                                             
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step                                                  
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 239, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 447, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/arah-release/im2mesh/metaavatar_render/lightning_model.py", line 174, in validation_step
    model_outputs = self.model(inputs, gen_cano_mesh=False, eval=True)
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/arah-release/im2mesh/metaavatar_render/models/__init__.py", line 200, in forward
    model_outputs = self.idhr_network(inputs)
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/arah-release/im2mesh/metaavatar_render/renderer/implicit_differentiable_renderer.py", line 209, in forward
    rgb_i, w_i = self.get_rbg_value_vol_sdf(sdf_network,
  File "/arah-release/im2mesh/metaavatar_render/renderer/implicit_differentiable_renderer.py", line 359, in get_rbg_value_vol_sdf
    valid_rgb.append(self.rendering_network(pi.squeeze(0), normal.squeeze(0), vi, feature_vectors, pose_cond))
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/arah-release/im2mesh/metaavatar_render/models/decoder.py", line 115, in forward
    x = lin(torch.cat([rendering_input, x], dim=-1))
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/envs/arah/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA out of memory. Tried to allocate 978.00 MiB (GPU 6; 23.70 GiB total capacity; 17.81 GiB already allocated; 665.31 MiB free; 20.93 GiB reserved in total by PyTorch) If reserve
d memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yijicheng** [comment]
I use my own training model to validate on zjumocap

**Comment by taconite** [comment]
I pushed some changes that optimize the memory usage - it solves some particular cases I encountered on my private dataset, but not sure if it can solve your case.

On the other hand, you can reduce the inference point batch size by setting `low_vram` to `True` when creating the model (for example usage, please refer [here](https://github.com/taconite/arah-release/blob/ef407178b00c28382457419b12e53155a839dc10/test.py#L65)). Particularly for validation changing this [line](https://github.com/taconite/arah-release/blob/ef407178b00c28382457419b12e53155a839dc10/validate.py#L65) from

`model = config.get_model(cfg, dataset=train_dataset, val_size=len(val_loader))`

to

`model = config.get_model(cfg, dataset=train_dataset, val_size=len(val_loader), low_vram=True)`

should help reducing memory usage, at the cost of slower inference speed.

**Comment by yijicheng** [comment]
Thank you so much!
