### ISSUE TITLE
Test error on custom dataset.

### ISSUE THREAD

**Issue by rexainn** [taconite/arah-release#32]
The training process is successfully finished. But when I test my own trained model, it has an error that `raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.`

Test command: `python test.py --num-workers 1 configs/arah-zju/rxy.yaml`

Error log:
```shell
 Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /home/jj/.conda/envs/arah/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [2]
Missing logger folder: out/arah-zju/ZJUMOCAP-313_4gpus/lightning_logs
Traceback (most recent call last):
  File "/DATA/DATA1/rxy_code/projects/202312_demo/arah-release/test.py", line 81, in <module>
    trainer.test(model=model, dataloaders=val_loader, verbose=True)
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_evaluating(self)
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 206, in start_evaluating
    self._results = trainer.run_stage()
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in run_stage
    return self._run_evaluate()
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1328, in _run_evaluate
    self._evaluation_loop._reload_evaluation_dataloaders()
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 168, in _reload_evaluation_dataloaders
    self.trainer.reset_test_dataloader()
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 568, in reset_test_dataloader
    self.num_test_batches, self.test_dataloaders = self._reset_eval_dataloader(
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 508, in _reset_eval_dataloader
    if has_len_all_ranks(dataloader, self.training_type_plugin, module)
  File "/home/jj/.conda/envs/arah/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 118, in has_len_all_ranks
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.
```

**Comment by rexainn** [comment]
It's my understanding fault. It should use `--pose-dir models`
