### ISSUE TITLE
"I have correctly set up the SMPL model, but it seems the dataset preprocessing script is unable to recognize the .pkl file."

### ISSUE THREAD

**Issue by soslsos16** [taconite/arah-release#39]
Traceback (most recent call last):
  File "/root/autodl-tmp/arah-release/preprocess_datasets/preprocess_ZJU-MoCap.py", line 38, in <module>
    body_model = BodyModel(bm_path='/root/autodl-tmp/arah-release/body_models/smpl/neutral/model.pkl', num_betas=10, batch_size=1,model_type='smpl').cuda()
  File "/root/miniconda3/envs/arah/lib/python3.9/site-packages/human_body_prior/body_model/body_model.py", line 67, in __init__
    else: raise ValueError('bm_path should be either a .pkl nor .npz file')
ValueError: bm_path should be either a .pkl nor .npz file

**Comment by taconite** [comment]
It seems like you have installed an alternative version of `human_body_prior` via anaconda. Can you uninstall it and make sure the `human_body_prior` module from [here](https://github.com/taconite/arah-release/tree/main/human_body_prior/body_model) is called?
