### ISSUE TITLE
Preprocessing dataet

### ISSUE THREAD

**Issue by wang-yan-adrian** [taconite/arah-release#40]
Hi, you have done a great job. I encountered some problems in data preprocessing. Can you help me solve it? Looking forward to your reply.

(6890, 3, 10)
Traceback (most recent call last):
  File "preprocess_datasets/preprocess_ZJU-MoCap.py", line 44, in <module>
    body_model = BodyModel(bm_path='body_models/smpl/neutral/model.pkl', num_betas=10, batch_size=1).cuda()
  File "/HDDdata/wangyan/arah-release-main/human_body_prior/body_model/body_model.py", line 75, in __init__
    self.register_buffer('shapedirs', torch.tensor(shapedirs, dtype=torch.float32).cuda())
ValueError: too many dimensions 'Select'

**Comment by ShenghaoJia** [comment]
I also encountered this issue, which was caused by a problem with the SMPL model. You can try printing the type of shapedirs. If the type is chumpy, you need to follow the instructions here to remove the chumpy object.
https://github.com/taconite/arah-release?tab=readme-ov-file#smpl-setup
